# bundle exec jekyll serve --host=0.0.0.0

title: MycilaShutterSpeedTester
description: ESP32 firmware to measure camera shutter speeds
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
